image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GOPROXY: "https://nexus.dr-test.ir/repository/go-proxy,direct"  # تنظیم GOPROXY برای استفاده از Nexus

stages:
  - build
  - test
  - dockerize
  - push

build-job:
  stage: build
  before_script:
    - apk add --no-cache go
  script:
    - go version
    - go mod tidy
    - go build -o myapp main.go
  artifacts:
    paths:
      - myapp

test-job:
  stage: test
  before_script:
    - apk add --no-cache go
  script:
    - go test -v ./...

dockerize-job:
  stage: dockerize
  script:
    - echo "🐳 Building Docker image..."
    - docker build -t myapp-image:$CI_COMMIT_REF_NAME .
  dependencies:
    - build-job
  artifacts:
    paths:
      - myapp

push-job:
  stage: push
  script:
    - echo "📤 Pushing Docker image..."
    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # - docker tag myapp-image:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  dependencies:
    - dockerize-job

