version: '3.7'

services:
  vault:
    image: docker.arvancloud.ir/hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root 
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200" 
    volumes:
      - vault_data:/vault/file 
    command: "vault server -dev"  

volumes:
  vault_data:

