apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:7.17.0
        ports:
        - containerPort: 5044    # پورت Beats
        - containerPort: 9600    # پورت رابط وب Logstash
        volumeMounts:
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-config  # متصل کردن ConfigMap به پاد
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 31437
  - port: 9600
    targetPort: 9600
    nodePort: 31438
